### Multi-variant Linear Regression Analysis, Regression Model

In [1]:
# Usual Imports
import numpy as np 
import time
import matplotlib.pyplot as plt

In [12]:
"""
Vector creation.

These all create a one dimensional vector (a), each with four elements. This is seen through the use of 
a.shape.
"""

a = np.zeros(4); print(f"np.zeros(4): a = {a}, a.shape = {a.shape}, a data type = {a.dtype}")

a = np.zeros((4,)); print(f"np.zeros((4,)): a = {a}, a.shape = {a.shape}, a data type = {a.dtype}")

a = np.random.random_sample(4); print(f"np.random.random_sample(4): a = {a}, a.shape = {a.shape}, a data type = {a.dtype}")

# Some data creation routines do not take a tuple, such as:
a = np.arange(4); print(f"np.arrange(4), {a} a.shape = {a.shape}, a data type = {a.dtype}")

a = np.random.randn(4); print(f"np.random.randn(4), {a} a.shape = {a.shape}, a data type = {a.dtype}")

# Finally values can also be specified manually too:
a = np.array([1,2,3,4]); print(f"np.array([1,2,3,4]), {a} a.shape = {a.shape}, a data type = {a.dtype}")

np.zeros(4): a = [0. 0. 0. 0.], a.shape = (4,), a data type = float64
np.zeros((4,)): a = [0. 0. 0. 0.], a.shape = (4,), a data type = float64
np.random.random_sample(4): a = [0.28468855 0.62932324 0.52452965 0.63475492], a.shape = (4,), a data type = float64
np.arrange(4), [0 1 2 3] a.shape = (4,), a data type = int32
np.random.randn(4), [-0.02387231 -0.03797087 -0.0096869   0.55262132] a.shape = (4,), a data type = float64
np.array([1,2,3,4]), [1 2 3 4] a.shape = (4,), a data type = int32


In [17]:
"""
Operations on vectors.
- Indexing
"""
# Data creation
a = np.arange(10); print(a)
# Access an element 
print(f"a[2] = {a[2]}")
# Accessing the last element, negitive indexing works from the end
print(f"a[-1] = {a[-1]}")
# Indexs must be within the range of the vector or will return an error
try:
    c = a[10]
except Exception as e:
    print("The error message you will see:")
    print(e)

[0 1 2 3 4 5 6 7 8 9]
a[2] = 2
a[-1] = 9
The error message you will see:
index 10 is out of bounds for axis 0 with size 10


In [27]:
"""
Operations on vectors.
- Slicing
"""
# Data creation
a = np.arange(10); print(f"a = {a}")
# Access 5 consecutive elements (START:STOP:STEP)
print(f"a[2:7:1] = {a[2:7:1]}")
# Access 3 elements seperated by 2
print(f"a[2:7:2] = {a[2:7:2]}")
# Access all elements index 3 and above
print(f"a[3:] = {a[3:]}")
# Access all elements below 3
print(f"a[:3] = {a[:3]}")
# Access all elements 
print(f"a[:] = {a[:]}")

a = [0 1 2 3 4 5 6 7 8 9]
a[2:7:1] = [2 3 4 5 6]
a[2:7:2] = [2 4 6]
a[3:] = [3 4 5 6 7 8 9]
a[:3] = [0 1 2]
a[:] = [0 1 2 3 4 5 6 7 8 9]


In [35]:
"""
Single vecotr operations.
"""
a = np.array([1, 2, 3, 4]); print(a)
# Negitive Elements 
print(f"-a = {-a}")
# Sum all elemetns of a 
print(f"np.sum(a) = {np.sum(a)}")
# Find the mean
print(f"np.mean(a) = {np.mean(a)}")
# Square each value
print(f"a**2 = {a**2}")

[1 2 3 4]
-a = [-1 -2 -3 -4]
np.sum(a) = 10
np.mean(a) = 2.5
a**2 = [ 1  4  9 16]


In [40]:
"""
Vector Vector (Element Wise Operations) 
"""
# Data creation
a = np.array([1, 2, 3, 4]) 
b = np.array([-1, -2, 3, 4])
# Binary Operations work element wise
# Addition
print(f"a + b = {a + b}")
# For this to work the vectors need to be of the same size
c = np.array([4, 5])
try:
    d = a + c
except Exception as e:
    print("Two different sized vectors gives us this error:")
    print(e)

a + b = [0 0 6 8]
Two different sized vectors gives us
operands could not be broadcast together with shapes (4,) (2,) 


In [42]:
"""
Scalar vecotor operations
"""
# Data creation
a = np.array([1, 2, 3, 4])

print(f"5 * a = {5 * a}")

5 * a = [ 5 10 15 20]


In [6]:
"""
Vector Vector Dot-Product.

The dot product multiplies the values of two vectors and sums the result. This means that the two vectors 
must be of the same size. Note that the dot product should return a scalar value.
Below is a naive python implmentation.
"""
def naive_dot(a, b):
    """
    Compute the dot product of two vectors 
    assuming they are the same size
    """
    
    x = 0
    for i in range(a.shape[0]):
        x = x + a[i] * b[i]
    return x

# Testing out naive_dot
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])

print(f"naive_dot(a, b) = {naive_dot(a, b)}")

naive_dot(a, b) = 24


In [8]:
"""
We can do the same using numpy, as shown below:
"""
# Same arrays as before
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])

print(f"np.dot(a, b) = {np.dot(a, b)}")

np.dot(a, b) = 24


In [19]:
"""
A comparison check of the speed vectorized code vs for loop is tested out below:
"""
a = np.random.randn(10000000)
b = np.random.randn(10000000)

tic = time.time() # Start time of vectorized code
c = np.dot(a, b)
toc = time.time()  # End time of vectorized code
print(f"Time for vectorised code is: {1000*(toc-tic):.4f}")

tic = time.time() # Start time of vectorized code
c = naive_dot(a, b)
toc = time.time()  # End time of vectorized code
print(f"Time for vectorised code is: {1000*(toc-tic):.4f}")


Time for vectorised code is: 6.0031
Time for vectorised code is: 3323.0011


In [25]:
"""
Matrix Creation
The same functions that are used to create 1D vectors can also be used to create nD arrays.
Here are some examples:
"""
print(np.zeros((1, 5)))

print(np.zeros((2, 1)))

print(np.random.random_sample((1,1)))

# These can also be used by manually specifying data.
print(np.array(([5], [4], [3])))

[[0. 0. 0. 0. 0.]]
[[0.]
 [0.]]
[[0.50240293]]
[[5]
 [4]
 [3]]


In [31]:
"""
Operations on Matrices
- Indexing
"""
# Data creation
a = np.arange(6).reshape(-1, 2)
print(a)
# Access and element
print(f"a[2,0] = {a[2,0]}")

# Access a row
print(f"a[2] = {a[2]}")

[[0 1]
 [2 3]
 [4 5]]
a[2,0] = 4
a[2] = [4 5]


In [39]:
"""
Operations on Matrices
Slicing a matrices is similar to a vector, using the (START:STOP:STEP) method.
- Slicing
"""
# Data creation
a = np.arange(20).reshape(-1, 10)
print(a)

# Access 5 consecutive elements 
print(f"a[0, 2:7:1] = {a[0, 2:7:1]}")

# Access 5 consecutive elements across two rows
print(f"a[:, 2:7:1] = {a[:, 2:7:1]}")

# Access all elements
print(f"a[:,:] = {a[:,:]}")

# Access all elements in row one
print(f"a[1,:] = {a[1,:]}")
# Same as
print(f"a[1] = {a[1]}")


[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[0, 2:7:1] = [2 3 4 5 6]
a[:, 2:7:1] = [[ 2  3  4  5  6]
 [12 13 14 15 16]]
a[:,:] = [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[1,:] = [10 11 12 13 14 15 16 17 18 19]
a[1] = [10 11 12 13 14 15 16 17 18 19]


In [4]:
"""
Multiple Varable Linear Regression.
Problem statement:
Same as the last example using housing prices, however this time there wil be three examples with four 
features (Size, bedrooms, floor and age).
"""
# Data creation
x_train = np.array([[2104, 5, 1, 45], 
                    [1416, 3, 2, 40], 
                    [852, 2, 1, 35]])

y_train = np.array([460, 232, 178])

x_train.shape

"""
We will now make vector w which will be the same length as x_train has features. In our case four. As usual 
b will be a single scalar value.
"""

b_init = 785.1811367994083
w_init = np.array([0.39133535, 18.75376741, -53.36032453, -26.42131618])

print(f"x_train.shape[1] should equal, w_init.shape[0] {x_train.shape[1]} == {w_init.shape[0]}")


x_train.shape[1] should equal, w_init.shape[0] 4 == 4


In [9]:
"""
Model prediction with multiple variables. Before we only had one variable now we have four.
Here we will create a function to calculate one predicted value based off one set of four variables.
"""

def predict(x, w, b):
    n = x.shape[0]
    f_wb = 0
    for i in range(n):
        p_i = w[i] * x[i]
        f_wb += p_i
    f_wb += b
    return f_wb

# Testing this function out on one row of data.
vector_x = x_train[0,:]

# Make a prediction
f_wb = predict(vector_x, w_init, b_init)
print(f"Prediction for the first row of data: {f_wb}")

Prediction for the first row of data: 459.9999976194083


In [12]:
"""
The next evolution of this is do perform a single prediction using vectorization and numpy.
This is show below:
"""

def predict(x, w, b):
    f_wb = np.dot(x, w) + b
    return f_wb

# Testing on the same example as last function  to ensure its the same.
f_wb = predict(vector_x, w_init, b_init)
print(f"Prediction for first row of data using numpy: {f_wb}")

Prediction for first row of data using numpy: 459.9999976194083


In [21]:
"""
Computing the cost with mutiple variables. This is much the same as before the only thing that changes is
the equation to find the predictied value, but we are to expect that.
"""

def compute_cost(X, y, w, b):
    m = X.shape[0]
    cost = 0
    for i in range(m):
        f_wb = np.dot(X[i], w) + b
        cost += (f_wb - y[i]) ** 2
    return cost / (2 * m) 

In [22]:
cost = compute_cost(x_train, y_train, w_init, b_init)
print(f'Cost at optimal w : {cost}')

Cost at optimal w : 1.5578904428966628e-12


#### Computing Gradients of the cost function for paramaters w and b

In [37]:
def compute_gradient(X, y, w, b):
    """
    Computes the gradient with multiple variables.
    Args:
    X - the features(m,n).
    y - our true labeled outputs(m,).
    w - weights array(n,).
    b - baise (scalar).
    Returns:
    dj_dw - Gradient of the cost for paramater w.
    dj_db - Gradient of the cost for paramater b. 
    """
    m,n = X.shape
    dj_dw = np.zeros((n,))
    dj_db = 0
    for i in range(m):
        error = (np.dot(X[i], w) + b) - y[i]
        for j in range(n):
            dj_dw[j] = dj_dw[j] + error * X[i, j]
        dj_db = dj_db + error
    dj_dw = dj_dw / m
    dj_db = dj_db /  m
    
    return dj_dw, dj_db

# Testing gradient funciton
tmp_dj_dw, tmp_dj_db = compute_gradient(x_train, y_train, w_init, b_init)
print(f"dj_dw: {tmp_dj_dw}")
print(f"dj_db: {tmp_dj_db}")


dj_dw: [-2.72623577e-03 -6.27197263e-06 -2.21745578e-06 -6.92403391e-05]
dj_db: -1.6739251501955248e-06


##### Performing Gradient Descent with multiple variables

In [ ]:
def graident_descent():
    """
    Performs gradient Descent to learn the best values for the parameters of w and b. By taking 
    num_gradient steps of size alpha (The learning rate).
    Args:
    x -
    y -
    w - 
    b -
    cost_function -
    gradient_function - 
    num_iterations -
    alpha - 
    Returns:
    w - 
    b -
    """